branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    - TEST_TYPE=Deployment
    - TEST_TYPE=Carthage
    - TEST_TYPE=CocoaPods
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
install:
- |
  if [ -n "$TEST_TYPE" ]; then
    bundle install
    if [ "$TEST_TYPE" == "Carthage" ]; then
      brew update
      brew install carthage || brew upgrade carthage
    fi
  fi
script:
- |
  RAKE_TASK_NAME=$(echo "$TEST_TYPE" | tr '[:upper:]' '[:lower:]')
  bundle exec rake test:$RAKE_TASK_NAME
after_success:
- |
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
